# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-08 23:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 9, 2, 41, 38, 48992), verbose_name='Опубликована'),
        ),
    ]
